import React from 'react';
import { cn } from '../../lib/utils';
import * as PhosphorIcons from '@phosphor-icons/react';

const {
  House,
  ChartBar,
  SquaresFour,
  Users,
  TreeStructure,
  ShoppingCart,
  Megaphone,
  Envelope,
  ShareNetwork,
  Lightning,
  Ticket,
  CurrencyDollar,
  Lifebuoy,
  Gear,
  Funnel,
  Pulse,
  Package,
  ChatCircle,
  ChatTeardrop,
  GitMerge,
  Sparkle,
  CaretDown,
  ArrowLeft,
  ArrowRight,
  CaretRight,
  CaretLeft,
  List,
  MagnifyingGlass,
  Sun,
  Moon,
  Bell,
  User,
  SignOut,
  Paperclip,
  DownloadSimple,
  Plus,
  DotsThreeVertical,
  PencilSimple,
  Phone,
  CalendarBlank,
  Target,
  TrendUp,
  CheckCircle,
  Warning,
  X,
  FacebookLogo,
  InstagramLogo,
  TwitterLogo,
  LinkedinLogo,
  YoutubeLogo,
  PinterestLogo,
  TiktokLogo,
  ArrowUp,
  ArrowDown,
  CreditCard,
  FileText,
  Flask,
  GitBranch,
  Cursor,
  Percent,
  WifiHigh,
  BatteryFull,
  Code,
  Minus,
  CornersOut,
  TextT,
  TextAlignLeft,
  TextAlignCenter,
  TextAlignRight,
  UserPlus,
  UserMinus,
  Question,
  Heart,
  Info,
  XCircle,
  Check,
  ArrowsClockwise,
  Eye,
  Pencil,
  Copy,
  Archive,
  Trash,
  UploadSimple,
  PlayCircle,
  PauseCircle,
  Image,
  Layout,
  Globe,
  BookmarkSimple,
  ThumbsUp,
  Smiley,
  MapPin,
  Star,
  Clock,
  WhatsappLogo
} = PhosphorIcons;

const iconMap: Record<string, React.ElementType> = {
  home: House,
  analytics: ChartBar,
  dashboard: SquaresFour,
  users: Users,
  segment: TreeStructure,
  shoppingCart: ShoppingCart,
  megaphone: Megaphone,
  mail: Envelope,
  share: ShareNetwork,
  zap: Lightning,
  ticket: Ticket,
  dollarSign: CurrencyDollar,
  lifeBuoy: Lifebuoy,
  settings: Gear,
  pipeline: Funnel,
  activity: Pulse,
  package: Package,
  messageSquare: ChatCircle,
  messageCircle: ChatTeardrop,
  workflow: GitMerge,
  sparkles: Sparkle,
  chevronDown: CaretDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronRight: CaretRight,
  chevronLeft: CaretLeft,
  menu: List,
  search: MagnifyingGlass,
  sun: Sun,
  moon: Moon,
  bell: Bell,
  user: User,
  logout: SignOut,
  paperclip: Paperclip,
  download: DownloadSimple,
  plus: Plus,
  moreVertical: DotsThreeVertical,
  edit: PencilSimple,
  phone: Phone,
  calendar: CalendarBlank,
  target: Target,
  trendingUp: TrendUp,
  checkCircle: CheckCircle,
  alertTriangle: Warning,
  close: X,
  facebook: FacebookLogo,
  instagram: InstagramLogo,
  tiktok: TiktokLogo,
  twitter: TwitterLogo,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  creditCard: CreditCard,
  fileText: FileText,
  beaker: Flask,
  'git-branch': GitBranch,
  mousePointer: Cursor,
  percent: Percent,
  barChart: ChartBar,
  wifi: WifiHigh,
  battery: BatteryFull,
  code: Code,
  minus: Minus,
  maximize: CornersOut,
  type: TextT,
  'align-left': TextAlignLeft,
  'align-center': TextAlignCenter,
  'align-right': TextAlignRight,
  userPlus: UserPlus,
  userMinus: UserMinus,
  helpCircle: Question,
  userX: UserMinus,
  heart: Heart,
  box: Package,
  info: Info,
  xCircle: XCircle,
  check: Check,
  refreshCw: ArrowsClockwise,
  eye: Eye,
  edit2: Pencil,
  linkedin: LinkedinLogo,
  youtube: YoutubeLogo,
  pinterest: PinterestLogo,
  copy: Copy,
  archive: Archive,
  trash: Trash,
  upload: UploadSimple,
  play: PlayCircle,
  pause: PauseCircle,
  image: Image,
  layout: Layout,
  grid: SquaresFour,
  list: List,
  globe: Globe,
  bookmark: BookmarkSimple,
  thumbsUp: ThumbsUp,
  smile: Smiley,
  mapPin: MapPin,
  star: Star,
  clock: Clock,
  whatsapp: WhatsappLogo
};

export interface IconProps {
  name: string;
  className?: string;
  size?: number | string;
  weight?: 'thin' | 'light' | 'regular' | 'bold' | 'fill' | 'duotone';
}

const IconComponent: React.FC<IconProps> = ({
  name,
  className,
  size = 20,
  weight = 'regular',
  ...wrapperProps
}) => {
  const Component = iconMap[name];

  if (!Component) {
    console.warn(`Icon "${name}" not found`);
    return (
      <span className={className} {...wrapperProps}>
        <Info size={size} weight={weight} />
      </span>
    );
  }

  return (
    <span className={cn("inline-flex items-center justify-center", className)} {...wrapperProps}>
      <Component size={size} weight={weight} />
    </span>
  );
};

export const Icon = Object.assign(IconComponent, { icons: iconMap });
